name: Config Wizard GitHub Action

on: [push]  

jobs:
  build-and-package:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Git Bash environment
        run: |
          "C:\Program Files\Git\bin\bash.exe" -c "cd /c/github/telegraf_custom/build_qmonitor && ./build_all.sh"

      - name: Copy and rename telegraf executable
        shell: cmd  
        run: |
          SET "sourceDir=/c/github/telegraf_custom/build_qmonitor"
          SET "destDir=C:\github\QuantumMonitor\artifacts"
          SET "pattern=telegraf_?.?.?.exe"
          FOR /F "delims=" %%F IN ('dir "%sourceDir%\%pattern%" /B /A:-D') DO (
              COPY "%sourceDir%\%%F" "%destDir%\telegraf.exe" /Y
          )

      - name: Setup Visual Studio Environment
        run: |
          CALL "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat"

      - name: Run buildmsi PowerShell script
        shell: powershell
        run: |
          powershell -ExecutionPolicy Bypass -File "C:\github\QuantumMonitor\WixSetup\buildmsi.ps1"
