name: Config Wizard GitHub Action

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: self-hosted 
    steps:
    - uses: actions/checkout@v2

    - name: Execute build_cw.bat
      run: .\build_cw.bat
      shell: cmd

    - name: Upload MSI to GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: C:\github\QuantumMonitor\WixSetup\bin\Release\*.msi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}