name: GitHub Actions Demo
run-name: Received commit from ${{ github.actor }}, initiating DEV publishing.
on: [push]
jobs:
  build-and-deploy:
    runs-on: windows-latest #giro in locale perchè tanto l'agent esisterà solo su server di test

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0'  #da verificare se va bene per tutti i progetti

    - name: Restore dependencies
      run: dotnet restore niente/niente/niente.sln #non ho capito se serve

    - name: Build
      run: dotnet build niente/niente/niente.sln --no-restore --configuration Release # Build

    - name: Publish
      run: dotnet publish niente/niente/niente.sln --no-restore --configuration Release --output ./publish 
      # Publish (di default ti trovi tutto in dovehaiinstallatoagentgithub/_work)


    #- name: Execute PowerShell Script
      #run: .\prova.ps1 #mettere path al nostro production-deploy.ps1
      #shell: pwsh 
      #questo non va, da errore che manca pwsh