name: GitHub Actions Demo
run-name: Received commit from ${{ github.actor }}, initiating DEV publishing.
on: [push]
jobs:
  build-and-deploy:
    runs-on: self-hosted  # Specify that this job runs on a self-hosted runner

    steps:
    - uses: actions/checkout@v4
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0'  # Specify the .NET version you need

    - name: Restore dependencies
      run: dotnet restore niente/niente/niente.sln
      # Restores the dependencies and tools of a project

    - name: Build
      run: dotnet build niente/niente/niente.sln --no-restore --configuration Release
      # Builds the project and its dependencies

    - name: Publish
      run: dotnet publish niente/niente/niente.sln --no-restore --configuration Release --output ./publish
      # Publishes the application and its dependencies to a folder for deployment


    #- name: Execute Deployment Script
      #run: powershell.exe -File ./deploy-script.ps1
      # Runs your PowerShell deployment scr