name: Config Wizard GitHub Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted 
    defaults:
      run:
        shell: powershell

    steps:
    - uses: actions/checkout@v2

    - name: Set up MSBuild path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build Custom Telegraf and Copy Artifacts
      run: |
        & "C:\Program Files\Git\bin\bash.exe" -c "cd /c/github/telegraf_custom/build_qmonitor && ./build_all.sh"
        $sourceDir = "/c/github/telegraf_custom/build_qmonitor"
        $destDir = "C:\github\QuantumMonitor\artifacts"
        $pattern = "telegraf_?.?.?.exe"
        Get-ChildItem "$sourceDir\$pattern" | ForEach-Object {
          Copy-Item "$sourceDir\$_" "$destDir\telegraf.exe" -Force
        }
        & "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat"
        & "C:\github\QuantumMonitor\WixSetup\buildmsi.ps1"

    - name: Upload MSI Installer
      uses: actions/upload-artifact@v2
      with:
        name: MSI-Installer
        path: C:\github\QuantumMonitor\WixSetup\bin\Release\*.msi