name: GitHub Actions Demo
run-name: Received commit from ${{ github.actor }}, initiating DEV publishing
on: [push]
jobs:
  execute-powershell:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Execute PowerShell Script
      run: .\_work\prova.ps1
      shell: pwsh 
